env: "dev"
http_server:
  address: "localhost:8081"
  timeout: 4s
  idle_timeout: 60s

storage:
  postgres:
    max_open_conns: 100
    max_idle_conns: 50
    max_idle_time: 10m
    conn_attempts: 10
    base_retry_delay: 100ms
    max_retry_delay: 5s